### PR TITLE
feat: add students

### PR DESCRIPTION
**Pull request by danieldietzler**

### CODE REVIEW

**Review by Lama64 — APPROVED** [review]
Passt so.
Dieses Controller Thema muss mich noch überzeugen, aber würde erstmal so lassen, wird schon einen Sinn haben.

**Comment by SuperMarcomen** [comment]
As stated by yourself too, I find the IStudentService interface superfluous. But everything else is fine!

**Review by SuperMarcomen — CHANGES_REQUESTED** [review]
As stated by yourself too, I find the IStudentService interface superfluous. But everything else is fine!

**Review by SuperMarcomen — APPROVED** [review]
Perfect!

**Pull request merged**
